export const JOB_STATUS = {
  LEAD: "LEAD",
  QUOTED: "QUOTED",
  AWAITING_DEPOSIT: "AWAITING_DEPOSIT",
  BOOKED: "BOOKED",
  AWAITING_PARTS: "AWAITING_PARTS",
  IN_PROGRESS: "IN_PROGRESS",
  AWAITING_REVIEW: "AWAITING_REVIEW",
  FINAL_INSPECTION: "FINAL_INSPECTION",
  READY_FOR_COLLECTION: "READY_FOR_COLLECTION",
  COMPLETED: "COMPLETED",
  INVOICED: "INVOICED",
  PAID: "PAID",
  LOST: "LOST",
} as const;

export type JobStatus = (typeof JOB_STATUS)[keyof typeof JOB_STATUS];

export const WORKSHOP_STATUS_SEQUENCE = [
  JOB_STATUS.BOOKED,
  JOB_STATUS.AWAITING_PARTS,
  JOB_STATUS.IN_PROGRESS,
  JOB_STATUS.AWAITING_REVIEW,
  JOB_STATUS.FINAL_INSPECTION,
  JOB_STATUS.READY_FOR_COLLECTION,
  JOB_STATUS.INVOICED,
  JOB_STATUS.COMPLETED,
] as const;

export const formatJobStatus = (status: JobStatus) =>
  status
    .toLowerCase()
    .split("_")
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(" ");
