export const JOB_STATUS = {
  LEAD: "LEAD",
  QUOTED: "QUOTED",
  AWAITING_DEPOSIT: "AWAITING_DEPOSIT",
  BOOKED: "BOOKED",
  AWAITING_PARTS: "AWAITING_PARTS",
  IN_PROGRESS: "IN_PROGRESS",
  AWAITING_REVIEW: "AWAITING_REVIEW",
  FINAL_INSPECTION: "FINAL_INSPECTION",
  READY_FOR_COLLECTION: "READY_FOR_COLLECTION",
  COMPLETED: "COMPLETED",
  INVOICED: "INVOICED",
  PAID: "PAID",
  LOST: "LOST",
} as const;

export const JOB_STATUS_MESSAGES: Record<JobStatus, string> = {
  LEAD: "Lead Created",
  QUOTED: "Quotation Issued",
  AWAITING_DEPOSIT: "Customer Accepted Quotation",
  BOOKED: "Vehicle Booked",
  AWAITING_PARTS: "Awaiting Parts",
  IN_PROGRESS: "Job Started",
  AWAITING_REVIEW: "Awaiting Review",
  FINAL_INSPECTION: "Final Inspection",
  READY_FOR_COLLECTION: "Ready For Collection",
  COMPLETED: "Job Completed",
  INVOICED: "Invoice Issued",
  PAID: "Invoice Paid",
  LOST: "Lead Marked As Lost",
};

export type JobStatus = (typeof JOB_STATUS)[keyof typeof JOB_STATUS];

export const LEAD_STATUSES: JobStatus[] = [
  JOB_STATUS.LEAD,
  JOB_STATUS.QUOTED,
  JOB_STATUS.LOST,
];

export const ACTIVE_JOB_STATUSES: JobStatus[] = [
  JOB_STATUS.AWAITING_DEPOSIT,
  JOB_STATUS.BOOKED,
  JOB_STATUS.AWAITING_PARTS,
  JOB_STATUS.IN_PROGRESS,
  JOB_STATUS.AWAITING_REVIEW,
  JOB_STATUS.FINAL_INSPECTION,
  JOB_STATUS.READY_FOR_COLLECTION,
  JOB_STATUS.COMPLETED,
];

export const JOB_TRANSITIONS: Partial<Record<JobStatus, readonly JobStatus[]>> =
  {
    [JOB_STATUS.LEAD]: [JOB_STATUS.QUOTED, JOB_STATUS.LOST],

    [JOB_STATUS.QUOTED]: [JOB_STATUS.AWAITING_DEPOSIT, JOB_STATUS.LOST],

    [JOB_STATUS.AWAITING_DEPOSIT]: [JOB_STATUS.BOOKED],

    [JOB_STATUS.BOOKED]: [JOB_STATUS.AWAITING_PARTS, JOB_STATUS.IN_PROGRESS],

    [JOB_STATUS.AWAITING_PARTS]: [JOB_STATUS.IN_PROGRESS],

    [JOB_STATUS.IN_PROGRESS]: [
      JOB_STATUS.AWAITING_REVIEW,
      JOB_STATUS.FINAL_INSPECTION,
      JOB_STATUS.READY_FOR_COLLECTION,
    ],

    [JOB_STATUS.AWAITING_REVIEW]: [JOB_STATUS.FINAL_INSPECTION],

    [JOB_STATUS.FINAL_INSPECTION]: [JOB_STATUS.READY_FOR_COLLECTION],

    [JOB_STATUS.READY_FOR_COLLECTION]: [JOB_STATUS.COMPLETED],
  };
